name: Challenge PR
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  build-challenge:
    runs-on: ubuntu-latest
    steps:
      - run: tokens=$(echo ${{github.head_ref}} | tr "/" "\n")
      - run: for token in $tokens do echo "> [$token]" done
