name: Challenge Update
on:
  pull_request:
    types: [closed]
jobs:
  Update-GCP-Dynamic:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - run: |
          branch=${{github.head_ref}}
          resourceName="${branch//'/'/-}"
          echo "resourceName=$resourceName" >> $GITHUB_ENV
      - name: Check for Dockerfile
        id: check_dockerfile
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "challenges/${{ github.head_ref }}/Dockerfile"
      - name: Check for Static Folder
        id: check_static
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "challenges/${{ github.head_ref }}/static" 
      - name: Build and Upload Challenge
        if: steps.check_dockerfile.outputs.files_exists == 'true'
        uses: piotr-krusinski/action-google-artifact-registry@v1.0
        with:
          # Google project ID of your project where Artifact Registry is created
          google_project_id: ${{ secrets.project_id }}
          # Google Artifact Registry region
          google_artifact_registry_region: ""
          # Google Artifact Registry hostname
          google_artifact_registry_hostname: ${{ secrets.registry_hostname }}
          # Google Artifact Registry repository name
          google_artifact_registry_name: ${{ secrets.registry_name }}
          # Base64 version of Google Cloud Platform service key to access Artifact Registry
          service_account_key: ${{ secrets.account_key }}
          # Path to dockerfile
          dockerfile: "challenges/${{github.head_ref}}/Dockerfile"
          # Name of created image
          image_name: ${{github.head_ref}}
      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account:  ${{ secrets.service_account }}
      - name: Update Cloud Run
        if: steps.check_dockerfile.outputs.files_exists == 'true'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.resourceName }}'
          image: "gcr.io/${{ secrets.registry_hostname }}/${{ secrets.project_id }}/${{ secrets.registry_name }}/${{ github.head_ref }}"
      - name: Upload Static Files
        if: steps.check_static.outputs.files_exists == 'true'
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'challenges/${{github.head_ref}}/static'
          destination: '${{secrets.bucket_name}}/challenges/${{github.head_ref}}/static' #TODO check if this is correct
