name: Challenge PR
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Check for Dockerfile
        id: check_dockerfile
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "challenges/${{ github.head_ref }}/Dockerfile"
      - name: Build docker image
        if: steps.check_dockerfile.outputs.files_exists == 'true'
        run: |
          docker build "challenges/${{ github.head_ref }}"
