name: CTFD Update
on:
  push:
    paths:
      - CTFd/**
      - config/ctfd-cr.yaml
jobs:
  Update-CTFD:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Authenticate with GCP
        id: gcp-auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.workload_identity_provider_id }}
          project_id:  ${{ secrets.project_id }}
          service_account: ${{ secrets.ar_push_service_account }}
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: ${{ steps.gcp-auth.outputs.access_token }}
          registry: ${{ secrets.registry_hostname }}
      - name: Build and Push Container
        run: |-
          docker build -t "${{ secrets.registry_hostname }}/${{ secrets.project_id }}/${{ secrets.registry_name }}/ctfd:${{ github.sha }}" CTFd
          docker push "${{ secrets.registry_hostname }}/${{ secrets.project_id }}/${{ secrets.registry_name }}/ctfd:${{ github.sha }}"
      - name: Modify CTFd Cloud Run YAML
        uses: teunmooij/yaml@v1
        with:
          from-file: config/ctfd-cr.yaml
          to-file: config/ctfd-cr.yaml
          merge: { 'spec.template.spec.containers': [ { 'image': "gcr.io/${{ secrets.registry_hostname }}/${{ secrets.project_id }}/${{ secrets.registry_name }}/ctfd:${{ github.sha }}" } ] }
      - name: Test YAML
        run: cat confit/ctfd-cr.yaml
      - name: Update Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          metadata: config/ctfd-cr.yaml